DROP TABLE IF EXISTS WEATHER_INFO;

CREATE TABLE WEATHER_INFO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  CITY_NAME VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(250) DEFAULT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);